apiVersion: v1
kind: Service
metadata:
  name: reservation-service
spec:
  type: NodePort  
  selector:
    app: reservation
  ports:
  - protocol: TCP
    port: 80       # Port interne du service
    targetPort: 3004  # Port du pod
    nodePort: 30081  # Port externe